#!/bin/bash
# Copyright 2020 DataStax, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pyinstaller -F $PARENT_PATH/sperf
[ -d $PARENT_PATH/../dist/build ] || mkdir $PARENT_PATH/../dist/build

ZIP=$PARENT_PATH/../dist/build/sperf-$TRAVIS_OS_NAME.zip
echo "zipping up $ZIP"
if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    zip -j -D $ZIP $PARENT_PATH/../dist/sperf.exe
else
    zip -j -D $ZIP $PARENT_PATH/../dist/sperf
fi
echo "files in build directory: $(ls $PARENT_PATH/../dist/build/)"
