name: go test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ ubuntu-latest, macos-latest, windows-latest ]
            go: [1.15]
    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
      with:
          go-version: ${{ matrix.go }}
    - name: Run tests
      shell: bash
      run: ./go test -v ./...